services:

  db-postgress:
    image: postgres
    restart: always
    shm_size: 128mb
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: example

  db-redis:
    image: redis
    restart: always
    expose:
      - 6379

  db-mysql:
    image: mysql
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: taskqueue

  test-container:
    build: .
    environment:
      - POSTGRES_DATABASE_URL=postgres://postgres:example@db-postgress:5432/postgres
      - MYSQL_DATABASE_URL=mysql://root:example@db-mysql:3306/taskqueue
      - REDIS_HOST=db-redis

    depends_on:
      - db-postgress
      - db-redis
