services:

  db-postgress:
    image: postgres
    restart: always
    shm_size: 128mb
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: example

  db-redis:
    image: redis
    restart: always
    expose:
      - 6379

  test-container:
    build: .
    environment:
      - POSTGRES_DATABASE_URL=postgres://postgres:example@db-postgress:5432/postgres
      - REDIS_HOST=db-redis

    depends_on:
      - db-postgress
      - db-redis
